version: '3'
services:
    model:
        build: .
        container_name: astromer
        volumes:
            - ./:/home/astronaut/astromer
        ports:
            - 6006:6006
            - 8888:8888
        #runtime: nvidia
        stdin_open: true # docker run -i
        # tty: true        # docker run -t
