
exp_id: 'lfgr-dropout' 
do_ft: [True, True]
do_clf: [True, True]
visible_gpu: ['0']

pretrain:
  tag: ['classic', 'pearson']
  weights: ['./presentation/results/lfgr/2024-04-02_22-26-03/',
            './presentation/results/lfgr/2024-04-05_14-31-32/']

data:
  paths : ['./data/records/alcock/fold_0/alcock_20', 
           './data/records/alcock/fold_1/alcock_20',
           './data/records/alcock/fold_2/alcock_20',
           './data/records/alcock/fold_0/alcock_100', 
           './data/records/alcock/fold_1/alcock_100',
           './data/records/alcock/fold_2/alcock_100',
           './data/records/alcock/fold_0/alcock_500', 
           './data/records/alcock/fold_1/alcock_500',
           './data/records/alcock/fold_2/alcock_500',

           './data/records/atlas/fold_0/atlas_20', 
           './data/records/atlas/fold_1/atlas_20',
           './data/records/atlas/fold_2/atlas_20',
           './data/records/atlas/fold_0/atlas_100', 
           './data/records/atlas/fold_1/atlas_100',
           './data/records/atlas/fold_2/atlas_100',
           './data/records/atlas/fold_0/atlas_500', 
           './data/records/atlas/fold_1/atlas_500',
           './data/records/atlas/fold_2/atlas_500',
         ]

  target : ['macho/fold_0/macho_20', 
            'macho/fold_1/macho_20',
            'macho/fold_2/macho_20',
            'macho/fold_0/macho_100', 
            'macho/fold_1/macho_100',
            'macho/fold_2/macho_100',
            'macho/fold_0/macho_500', 
            'macho/fold_1/macho_500',
            'macho/fold_2/macho_500',

            'atlas/fold_0/atlas_20', 
            'atlas/fold_1/atlas_20',
            'atlas/fold_2/atlas_20',
            'atlas/fold_0/atlas_100', 
            'atlas/fold_1/atlas_100',
            'atlas/fold_2/atlas_100',
            'atlas/fold_0/atlas_500', 
            'atlas/fold_1/atlas_500',
            'atlas/fold_2/atlas_500',
         ]

finetuning:
  lr : 0.001
  scheduler: False
  batch_size : 512
  patience : 30
  num_epochs : 10000
  probed : 0.2
  debug : False
  
classification:
  lr : 0.001
  batch_size : 512
  patience : 30
  num_epochs : 10000
  clf_arch: 'avg_mlp'
  astromer_trainable: False
  debug : False
  

