
exp_id: 'temperature' 
do_ft: [True, True, True, True, True, True]
do_clf: [True, True, True, True, True, True]
visible_gpu: ['3']

pretrain:
  tag: ['zero_1e5', 'zero_1e3', 'zero_clean', 'temp_02', 'temp_04', 'temp_08']
  weights: ['./presentation/results/zero/2024-04-23_22-40-56',
            './presentation/results/zero/2024-04-24_16-13-23',
            './presentation/results/zero/2024-04-29_05-06-25',
            './presentation/results/temp/2024-04-13_04-04-34',
            './presentation/results/temp/2024-04-18_20-49-50',
            './presentation/results/temp/2024-04-24_01-07-33' ]

data:
  paths : ['./data/records/alcock/fold_0/alcock_20', 
           './data/records/alcock/fold_1/alcock_20',
           './data/records/alcock/fold_2/alcock_20',
           './data/records/alcock/fold_0/alcock_100', 
           './data/records/alcock/fold_1/alcock_100',
           './data/records/alcock/fold_2/alcock_100',
           './data/records/alcock/fold_0/alcock_500', 
           './data/records/alcock/fold_1/alcock_500',
           './data/records/alcock/fold_2/alcock_500',

           './data/records/atlas/fold_0/atlas_20', 
           './data/records/atlas/fold_1/atlas_20',
           './data/records/atlas/fold_2/atlas_20',
           './data/records/atlas/fold_0/atlas_100', 
           './data/records/atlas/fold_1/atlas_100',
           './data/records/atlas/fold_2/atlas_100',
           './data/records/atlas/fold_0/atlas_500', 
           './data/records/atlas/fold_1/atlas_500',
           './data/records/atlas/fold_2/atlas_500',
         ]

  target : ['macho/fold_0/macho_20', 
            'macho/fold_1/macho_20',
            'macho/fold_2/macho_20',
            'macho/fold_0/macho_100', 
            'macho/fold_1/macho_100',
            'macho/fold_2/macho_100',
            'macho/fold_0/macho_500', 
            'macho/fold_1/macho_500',
            'macho/fold_2/macho_500',

            'atlas/fold_0/atlas_20', 
            'atlas/fold_1/atlas_20',
            'atlas/fold_2/atlas_20',
            'atlas/fold_0/atlas_100', 
            'atlas/fold_1/atlas_100',
            'atlas/fold_2/atlas_100',
            'atlas/fold_0/atlas_500', 
            'atlas/fold_1/atlas_500',
            'atlas/fold_2/atlas_500',
         ]

finetuning:
  lr : 0.00001
  scheduler: False
  batch_size : 1024
  patience : 20
  num_epochs : 10000
  probed : 0.2
  debug : False
  
classification:
  lr : 0.001
  batch_size : 512
  patience : 20
  num_epochs : 10000
  clf_arch: ['avg_mlp', 'skip_avg_mlp']
  astromer_trainable: False
  debug : False
  

