
exp_id: 'temperature' 
do_ft: [False]
do_clf: [True]
visible_gpu: ['0']

pretrain:
  tag: ['zero_0']
  weights: ['./presentation/results/temp/2024-04-13_04-04-34']

data:
  paths : ['./data/records/alcock/fold_0/alcock_20', 
           './data/records/alcock/fold_1/alcock_20',
           './data/records/alcock/fold_2/alcock_20',
           './data/records/alcock/fold_0/alcock_100', 
           './data/records/alcock/fold_1/alcock_100',
           './data/records/alcock/fold_2/alcock_100',
           './data/records/alcock/fold_0/alcock_500', 
           './data/records/alcock/fold_1/alcock_500',
           './data/records/alcock/fold_2/alcock_500',

           './data/records/atlas/fold_0/atlas_20', 
           './data/records/atlas/fold_1/atlas_20',
           './data/records/atlas/fold_2/atlas_20',
           './data/records/atlas/fold_0/atlas_100', 
           './data/records/atlas/fold_1/atlas_100',
           './data/records/atlas/fold_2/atlas_100',
           './data/records/atlas/fold_0/atlas_500', 
           './data/records/atlas/fold_1/atlas_500',
           './data/records/atlas/fold_2/atlas_500',
         ]

  target : ['macho/fold_0/macho_20', 
            'macho/fold_1/macho_20',
            'macho/fold_2/macho_20',
            'macho/fold_0/macho_100', 
            'macho/fold_1/macho_100',
            'macho/fold_2/macho_100',
            'macho/fold_0/macho_500', 
            'macho/fold_1/macho_500',
            'macho/fold_2/macho_500',

            'atlas/fold_0/atlas_20', 
            'atlas/fold_1/atlas_20',
            'atlas/fold_2/atlas_20',
            'atlas/fold_0/atlas_100', 
            'atlas/fold_1/atlas_100',
            'atlas/fold_2/atlas_100',
            'atlas/fold_0/atlas_500', 
            'atlas/fold_1/atlas_500',
            'atlas/fold_2/atlas_500',
         ]

finetuning:
  lr : 0.00001
  scheduler: False
  batch_size : 1024
  patience : 20
  num_epochs : 10000
  probed : 0.2
  debug : False
  
classification:
  lr : 0.001
  batch_size : 512
  patience : 20
  num_epochs : 10000
  clf_arch: ['avg_mlp', 'skip_avg_mlp']
  astromer_trainable: False
  debug : False
  

