[general]
code_root = "."
creation_date = "2022-10-20"
gpu = 0

[astromer]
layers = 2
heads = 4
head_dim = 64
dff = 128
dropout = 0.1
window_size = 200

[masking]
mask_frac = 0.5
rnd_frac = 0.2
same_frac = 0.2

[positional]
base = 1000
version = "v1"

[pretraining]
exp_path = "./results/template_pt/"
lr = 0.001
scheduler = true
epochs = 10000
patience = 20

[pretraining.data]
path = "./data/records/datest"
batch_size = 512
repeat = 4
sampling = true
normalize = true
shuffle_train = true
shuffle_val = false
shuffle_test = false
cache_train = true
cache_val = true
cache_test = false

[finetuning]
exp_path = "./results/finetuning/alcock/b/alcock_20_f1"
weights = "./weights/rf_macho"
lr = 0.001
scheduler = true
epochs = 10000
patience = 20
batch_size = 2500

[finetuning.data]
path = "./data/records/alcock/fold_1/alcock_20"
batch_size = 512
repeat = 1
sampling = false
normalize = true
shuffle_train = true
shuffle_val = false
shuffle_test = false
cache_train = true
cache_val = true
cache_test = false

[classification]
exp_path = "./results/classification/alcock/b/alcock_20_f1"
weights = "./results/finetuning/alcock/b/alcock_20_f1"
train_astromer = true
lr = 0.001
epochs = 10000
patience = 20
batch_size = 512

[classification.data]
path = "./data/records/alcock/fold_1/alcock_20"
batch_size = 512
repeat = 1
sampling = false
normalize = true
shuffle_train = true
shuffle_val = false
shuffle_test = false
cache_train = true
cache_val = true
cache_test = false
