exp_name = "mask_v_h_dan_05"
data = "./data/records/macho"
checkpoint = "-1"
gpu = "2"
debug = false
encoder_mode = "normal"
num_layers = 2
num_heads = 4
head_dim = 64
pe_dim = 256
pe_base = 1000
pe_exp = 1
mixer = 128
dropout = 0.0
avg_layers = false
lr = 1e-5
bs = 2500
patience = 20
num_epochs = 10000
window_size = 200
probed = 0.5
rs = 0.2
